name: Build Development-Version PR Status

on:
  pull_request:

jobs:
  build:
  
    name: Build and Test Development-Version
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write

    steps:
     - name: Check out project
       uses: actions/checkout@v3
      
     - name: Set up JDK 18
       uses: actions/setup-java@v3
       with:
          java-version: 18
          distribution: 'adopt'

     - name: Set up Node.js 16
       uses: actions/setup-node@v3
       with:
          node-version: 16
     
     - name: Cache Maven packages
       uses: actions/cache@v2
       with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
        
     - name: Build with Maven
       run: mvn -B package --file pom.xml
       
     - name: Run tests with Maven
       run: mvn -B clean test --file pom.xml  
