name: Build Production-Version Release

on:
  release:
    types: [created]

jobs:
  build:

    name: Build Production-Version
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'adopt'

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run Maven Package
        run: mvn -B clean package -Pproduction
        
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/pom.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

