name: Workflow Test Development-Version run on Pull Request & Push

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  run_tests:
  
    name: Test Development-Version
    runs-on: ubuntu-latest

    steps:
     - name: Check out project
       uses: actions/checkout@v3
        
     - name: Set up JDK 18
       uses: actions/setup-java@v3
       with:
         java-version: 18
         distribution: 'adopt'
          
     - name: Run tests with Maven
       run: mvn -B clean test --file pom.xml
