name: Build Production-Version PR Status

on:
  pull_request:
  
  push:
      
jobs:
  build:
  
    name: Build Production-Version
    runs-on: ubuntu-latest

    steps:
      - name: Check out project
        uses: actions/checkout@v3
        
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'adopt'
          cache: maven

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run Maven Package
        run: mvn -B package -Pproduction
